language: objective-c
osx_image: xcode611

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- (cd External/hoedown && make test)
- xcodebuild -project MarkdownKit.xcodeproj -scheme MarkdownKit test -sdk iphonesimulator8.1 | xcpretty -c
#- pod lib lint --quick
