language: objective-c
osx_image: xcode7.2

script:
- set -o pipefail
- (cd External/hoedown && make test)
- xcodebuild -project MarkdownKit.xcodeproj -scheme MarkdownKit test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- xcodebuild -project MarkdownKit.xcodeproj -scheme MarkdownKit-OSX test -sdk macosx | xcpretty -c
- pod lib lint --quick
